/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PositionsNewRouteImport } from './routes/positions/new'
import { Route as PositionsNewPoolsRouteImport } from './routes/positions/new/pools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsNewRoute = PositionsNewRouteImport.update({
  id: '/positions/new',
  path: '/positions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsNewPoolsRoute = PositionsNewPoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => PositionsNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/positions/new': typeof PositionsNewRouteWithChildren
  '/positions/new/pools': typeof PositionsNewPoolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/positions/new': typeof PositionsNewRouteWithChildren
  '/positions/new/pools': typeof PositionsNewPoolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/positions/new': typeof PositionsNewRouteWithChildren
  '/positions/new/pools': typeof PositionsNewPoolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/positions/new' | '/positions/new/pools'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/positions/new' | '/positions/new/pools'
  id: '__root__' | '/' | '/positions/new' | '/positions/new/pools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PositionsNewRoute: typeof PositionsNewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/new': {
      id: '/positions/new'
      path: '/positions/new'
      fullPath: '/positions/new'
      preLoaderRoute: typeof PositionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/new/pools': {
      id: '/positions/new/pools'
      path: '/pools'
      fullPath: '/positions/new/pools'
      preLoaderRoute: typeof PositionsNewPoolsRouteImport
      parentRoute: typeof PositionsNewRoute
    }
  }
}

interface PositionsNewRouteChildren {
  PositionsNewPoolsRoute: typeof PositionsNewPoolsRoute
}

const PositionsNewRouteChildren: PositionsNewRouteChildren = {
  PositionsNewPoolsRoute: PositionsNewPoolsRoute,
}

const PositionsNewRouteWithChildren = PositionsNewRoute._addFileChildren(
  PositionsNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PositionsNewRoute: PositionsNewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
